_BASE_: "coco_R_50_FPN_CONV_1x.yaml"
MODEL:
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  WEIGHTS: "See Instructions"
  RESNETS:
    STRIDE_IN_1X1: False
INPUT:
  FORMAT: "RGB"
SOLVER:
  WEIGHT_DECAY: 0.000025
TEST:
  EVAL_PERIOD: 10000